### PR TITLE
Major update

### PR DESCRIPTION
**Pull request by amazingrando**
The Emulsify page for emulsify.info has undergone a redesign, dev, and write. 

## How to review
- Download this branch
- Run `gulp serve` and explore the site or visit https://5e46ae008492350009f4b402--romantic-allen-96bc34.netlify.com/
- [ ] Compare to the design below.
MacBook Pro - 1

### CODE REVIEW

**Comment by evanmwillhite** [comment]
This looks fantastic! I have some copy changes to request.

`Bring order to chaos`:
```
- Scale your design system for any size organization and properties
- Share components and documentation for all properties
```

`Solve accessibility issues`:
```
When a problem is fixed in one place, it’s fixed everywhere!
Automated testing built into process across all properties
```

`Build it your way`
```
Emulsify includes support for multiple languages including HTML, Twig and React
Is extendable for other languages
```

**Comment by evanmwillhite** [comment]
I think this line `Built-in testing for accessibility, browser support, and more` should probably change to `Built-in testing for accessibility and more through rich add-on ecosystems`

**Comment by ModulesUnraveled** [comment]
Here's my two cents on the verbiage:
`Bring order to chaos`:
```
- Scale your design system to fit your organization whether you have one property or many
- Share components and documentation across all properties
```

`Solve accessibility issues`:
```
Write accessible code once, and all of your projects benefit!
Automated testing is built into the development process for all properties
```

`Build it your way`
```
Emulsify supports many languages including HTML, Twig and React out of the box
Support other languages through plugins
```

**Comment by ModulesUnraveled** [comment]
I agree with Evan about this line, although, I'd add the word "a":
> Built-in testing for accessibility and more through a rich add-on ecosystems

**Comment by amazingrando** [comment]
@ModulesUnraveled I looked into IE on emulsify.info and in the last 13 months we have had 27 people on any version of IE. (See screenshot below.)

Screenshot 2020-02-14 16 37 04

I added a note at the top of the page for IE.
Screenshot 2020-02-14 17 07 22

**Comment by astanush** [comment]
Let’s go with @ModulesUnraveled copy here: https://github.com/fourkitchens/emulsify-landingpage/pull/18#issuecomment-586392106

And I agree with adding the “a”, but then shouldn’t “ecosystem” be singular?

> Built-in testing for accessibility and more through a rich add-on ecosystem

**Comment by evanmwillhite** [comment]
Can we change docs link to https://docs.emulsify.info/ ? Otherwise looks great to me!

**Pull request merged**
