### PR TITLE
Emulsify 5 signup

### PR DESCRIPTION
**Pull request by amazingrando**
This PR adds a sign up form for visitors to get updates on Emulsify 5.

## How to Review
- [ ] Confirm that the sign up form right under the header looks like the image below.

Screenshot 2019-07-11 16 54 59

### CODE REVIEW

**Comment by astanush** [comment]
@amazingrando I think we should be using the non-hyphenated version of "up to date" https://grammarist.com/usage/up-to-date/

**Comment by astanush** [comment]
@amazingrando I like the decision not to center all the elements within the sign up area, but maybe the container should be centered with the elements in the header above it?

61085024-46b79300-a3fd-11e9-99f0-9822931b1bb0

**Comment by amazingrando** [comment]
@astanush Changes have been made (and I learned about "up to date"!)

Screenshot 2019-07-12 12 20 52

**Comment by astanush** [comment]
Looks good to me! Let me know if I can help test form submissions when it's ready to do so.

**Pull request merged**
